name: Dataflow

on:
  push:
    branches:
      - master
      - dev
    paths:
      - dataflow/**
      - .github/**
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

jobs:
  set-env:
    uses: ./.github/workflows/main.yaml


  build-template:
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: |-
          gcloud auth configure-docker
          docker build -t ${{ needs.set-env.outputs.image }} dataflow/
          docker push ${{ needs.set-env.outputs.image }}

  deploy-template:
    runs-on: ubuntu-latest
    needs:
      - set-env
      - build-template
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - uses: google-github-actions/setup-gcloud@v0
      
      - run: >-
          gcloud dataflow flex-template build ${{ needs.set-env.outputs.template }} \
            --image="${{ needs.set-env.outputs.image }}" \
            --sdk-language="PYTHON" \
            --metadata-file="dataflow/metadata.json"
