name: Function

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - dataflow/**
  workflow_dispatch:

concurrency: ${{ github.ref }}-${{ github.workflow }}

env:
  PROJECT_ID: voltaic-country-280607
  GCP_SA: bivuanem@voltaic-country-280607.iam.gserviceaccount.com
  ENV_FILE: env.yaml

jobs:
  set-env:
    uses: ./.github/workflows/main.yaml

  deploy-function:
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "INSIDER_API_KEY: ${{ secrets.INSIDER_API_KEY }}" >> ${{ env.ENV_FILE }}

          echo "TEMPLATE: ${{ needs.set-env.outputs.template }}" >> ${{ env.ENV_FILE }}

          echo "PUBLIC_URL: https://us-central1-${{ env.PROJECT_ID }}.cloudfunctions.net/${{ needs.set-env.outputs.fn }}" >> ${{ env.ENV_FILE }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - run: npm ci

      - run: tsc --sourceMap false

      - run: |
          cp package.json dist/package.json
          cp package-lock.json dist/package-lock.json

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: >-
          gcloud functions deploy ${{ needs.set-env.outputs.fn }}
          --entry-point=main
          --source=dist
          --region=us-central1
          --timeout=530
          --memory=256MB
          --runtime=nodejs16
          --trigger-http
          --no-user-output-enabled
          --service-account=${{ env.GCP_SA }}
          --env-vars-file=${{ env.ENV_FILE }}
          --allow-unauthenticated
  
